[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'kannnokanno/previm'

[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
  let g:gruvbox_contrast_dark = 'hard'
'''
[[plugins]]
repo='MichaelMure/mdr'
hook_add= '''
	let g:preview_markdown_vertical = 1
'''

#rust formatter
[[plugins]]
repo='rust-lang/rustfmt'

[[plugins]]
repo='rust-lang/rust.vim'
hook-add='''
	let g:rustfmt_autosave = 1
'''

#gcコマンドでコメントアウト
[[plugins]]
repo = 'tpope/vim-commentary'

#git操作をneovim内で
[[plugins]]
repo = 'lambdalisue/gina.vim'
hook_add = '''
  nmap <leader>gs <cmd>Gina status<cr>
'''
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  let g:gitgutter_map_keys = 0
  nmap ]c <Plug>(GitGutterNextHunk)
  nmap [c <Plug>(GitGutterPrevHunk)
'''
